import { DependencyGraph, ElementExpression } from "./types";

export class SignalCodeGenerator {
  private handlers: Record<string, any>;
  private componentName: string;
  
  constructor(
    private graph: DependencyGraph,
    handlers: Record<string, any> = {},
    componentName: string = 'App'
  ) {
    this.handlers = handlers;
    this.componentName = componentName;
  }
  
  /**
   * Generate the complete JavaScript code
   */
  generate(stateKeys: string[], computedKeys: string[]): string {
    const sections = [
      this.generateHeader(),
      this.generateUpdateFunctions(),
      this.generateRuntime(),
      this.generateSignalDeclarations(stateKeys),
      this.generateComputedValues(computedKeys),
      this.generateHandlerWrappers(),
      this.generateDevTools(),
      this.generateFooter()
    ];
    
    return sections.filter(Boolean).join('\n\n');
  }
  
  /**
   * Generate file header with metadata
   */
  private generateHeader(): string {
    return `// Generated by HJX v0.2 - Signal-based Reactivity
// Component: ${this.componentName}
// Generated: ${new Date().toISOString()}
// Elements: ${this.graph.metrics.totalElements}
// Expressions: ${this.graph.metrics.totalExpressions}
// Hot states: ${this.graph.metrics.hotStates.join(', ') || 'none'}
`;
  }
  
  /**
   * Generate runtime utilities
   */
  private generateRuntime(): string {
    return `
// Runtime utilities
let currentEffect = null;
let isBatching = false;
const batchQueue = new Set();
const initialState = ${JSON.stringify(Object.fromEntries(
      Array.from(this.graph.stateToElements.keys()).map(k => [k, null])
    ))};

function batch(fn) {
  isBatching = true;
  try { 
    fn(); 
  } finally {
    isBatching = false;
    batchQueue.forEach(f => f());
    batchQueue.clear();
  }
}

function subscribe(signal, fn) {
  if (!signal._subs) signal._subs = new Set();
  signal._subs.add(fn);
  return () => signal._subs.delete(fn);
}
`;
  }
  
  /**
   * Generate signal declarations with optimizations
   */
  private generateSignalDeclarations(keys: string[]): string {
    if (keys.length === 0) return '// No state variables';
    
    return keys.map(key => {
      const elements = this.graph.stateToElements.get(key) || new Set();
      const computedDeps = this.graph.stateToComputed.get(key) || new Set();
      const isHot = elements.size > 5 || computedDeps.size > 2;
      const updateCode = elements.size > 0 ? `updateDOM_${key}();` : '';
      
      return `
// Signal: ${key} (${elements.size} elements, ${computedDeps.size} computed deps)
let _${key} = initialState.${key};
const _${key}_subs = new Set();
let _${key}_batchTimer = null;

const ${key} = {
  get: () => {
    if (currentEffect) _${key}_subs.add(currentEffect);
    return _${key};
  },
  set: ${isHot ? this.generateHotSetFunction(key, updateCode) : this.generateColdSetFunction(key, updateCode)},
  subscribe: (fn) => {
    _${key}_subs.add(fn);
    return () => _${key}_subs.delete(fn);
  }
};`;
    }).join('\n');
  }
  
  /**
   * Generate optimized setter for hot state (batched updates)
   */
  private generateHotSetFunction(key: string, updateCode: string): string {
    return `(val) => {
      if (val === _${key}) return;
      _${key} = val;
      
      if (_${key}_batchTimer === null) {
        _${key}_batchTimer = Promise.resolve().then(() => {
          _${key}_batchTimer = null;
          // Notify subscribers
          _${key}_subs.forEach(fn => fn());
          // Update computed values
          ${this.getComputedDependents(key).map(c => `update_${c}();`).join('\n          ')}
          // Update DOM
          ${updateCode}
        });
      }
    }`;
  }
  
  /**
   * Generate immediate setter for cold state
   */
  private generateColdSetFunction(key: string, updateCode: string): string {
    return `(val) => {
      if (val === _${key}) return;
      _${key} = val;
      
      // Notify subscribers
      _${key}_subs.forEach(fn => fn());
      
      // Update computed values
      ${this.getComputedDependents(key).map(c => `update_${c}();`).join('\n      ')}
      
      // Update DOM
      ${updateCode}
    }`;
  }
  
  /**
   * Generate computed value functions with caching
   */
  private generateComputedValues(keys: string[]): string {
    if (keys.length === 0) return '// No computed values';
    
    return keys.map(key => {
      const deps = this.graph.computedDeps.get(key) || new Set();
      const expr = this.graph.computedExprs.get(key) || 'null';
      const depArray = Array.from(deps);
      
      return `
// Computed: ${key} (deps: ${depArray.join(', ')})
let _${key};
let _${key}_dirty = true;

function update_${key}() {
  if (!_${key}_dirty) return;
  
  const newVal = (() => {
    ${depArray.map(d => `const ${d}Val = ${d}.get();`).join('\n    ')}
    return ${this.convertExpression(expr)};
  })();
  
  if (newVal !== _${key}) {
    _${key} = newVal;
    _${key}_dirty = false;
    ${this.getComputedElementUpdates(key)}
  }
}

// Subscribe to dependencies
${depArray.map(d => `
{
  const unsub = subscribe(${d}, () => {
    _${key}_dirty = true;
    if (isBatching) batchQueue.add(update_${key});
    else update_${key}();
  });
  // Store for cleanup
  if (!window.__hjx_cleanups) window.__hjx_cleanups = [];
  window.__hjx_cleanups.push(unsub);
}
`).join('')}

// Initial computation
update_${key}();
`;
    }).join('\n');
  }
  
  /**
   * Convert HJX expression to JavaScript
   */
  private convertExpression(expr: string): string {
    // Replace state variable references with their signal getters
    return expr.replace(/\b([A-Za-z_][A-Za-z0-9_]*)\b/g, (match) => {
      if (this.graph.stateToElements.has(match) || this.graph.computedDeps.has(match)) {
        return `${match}.get()`;
      }
      return match;
    });
  }
  
  /**
   * Generate DOM update functions
   */
  private generateUpdateFunctions(): string {
    const functions: string[] = [];
    
    this.graph.stateToElements.forEach((elements, stateKey) => {
      if (elements.size === 0) return;
      
      const updates: string[] = [];
      elements.forEach(elementId => {
        const expressions = this.graph.elementExpressions.get(elementId) || [];
        expressions.forEach(expr => {
          if (expr.dependencies.has(stateKey)) {
            updates.push(this.generateElementUpdate(elementId, expr));
          }
        });
      });
      
      if (updates.length > 0) {
        const elementIds = Array.from(elements).join('"], [data-hjx-id="');
        functions.push(`
function updateDOM_${stateKey}() {
  const elements = document.querySelectorAll('[data-hjx-id="${elementIds}"]');
  elements.forEach(el => {
    ${updates.join('\n    ')}
  });
}`);
      }
    });
    
    return functions.join('\n');
  }
  
  /**
   * Generate update code for a specific element
   */
  private generateElementUpdate(elementId: string, expr: ElementExpression): string {
    switch (expr.type) {
      case 'text':
        return this.generateTextUpdate(elementId, expr);
      case 'attribute':
        return this.generateAttributeUpdate(elementId, expr);
      case 'condition':
        return this.generateConditionUpdate(elementId, expr);
      case 'loop':
        return this.generateLoopUpdate(elementId, expr);
      case 'binding':
        return this.generateBindingUpdate(elementId, expr);
      default:
        return '';
    }
  }
  
  /**
   * Generate text content update
   */
  private generateTextUpdate(elementId: string, expr: ElementExpression): string {
    const parts = expr.expression.split(/(\{\{\s*[^}]+\s*\}\})/g);
    const jsParts: string[] = [];
    
    for (const part of parts) {
      if (part.startsWith('{{') && part.endsWith('}}')) {
        const key = part.replace(/\{\{\s*|\s*\}\}/g, '').trim();
        const getter = key.includes('.')
          ? key.split('.').map((k, i) => i === 0 ? `${k}.get()` : `['${k}']`).join('')
          : `${key}.get()`;
        jsParts.push(`String(${getter} ?? '')`);
      } else if (part.trim()) {
        jsParts.push(JSON.stringify(part));
      }
    }

    return `
  if (el.getAttribute('data-hjx-id') === '${elementId}') {
    el.textContent = ${jsParts.join(' + ')};
  }`;
  }
  
  /**
   * Generate attribute update
   */
  private generateAttributeUpdate(elementId: string, expr: ElementExpression): string {
    const attr = expr.attribute!;
    const parts = expr.expression.split(/(\{\{\s*[^}]+\s*\}\})/g);
    const templateParts = parts.map(part => {
      if (part.startsWith('{{') && part.endsWith('}}')) {
        const key = part.replace(/\{\{\s*|\s*\}\}/g, '');
        const getter = key.includes('.') 
          ? key.split('.').map((k, i) => i === 0 ? `${k}.get()` : `['${k}']`).join('')
          : `${key}.get()`;
        return `\${${getter}}`;
      }
      return JSON.stringify(part);
    }).join(' + ');
    
    return `
  if (el.getAttribute('data-hjx-id') === '${elementId}') {
    const value = ${templateParts};
    if (value === false || value === null || value === undefined || value === 'false') {
      el.removeAttribute('${attr}');
    } else {
      el.setAttribute('${attr}', String(value));
    }
  }`;
  }
  
  /**
   * Generate condition update
   */
  private generateConditionUpdate(elementId: string, expr: ElementExpression): string {
    const condition = this.convertConditionToJS(expr.expression);
    
    return `
  if (el.getAttribute('data-hjx-id') === '${elementId}') {
    const show = ${condition};
    el.style.display = show ? '' : 'none';
  }`;
  }
  
  /**
   * Generate loop update
   */
  private generateLoopUpdate(elementId: string, expr: ElementExpression): string {
    const listName = expr.expression;
    const itemName = expr.item!;
    
    return `
  if (el.getAttribute('data-hjx-id') === '${elementId}') {
    const items = ${listName}.get();
    const template = el.querySelector('template');
    if (template && Array.isArray(items)) {
      const html = items.map((${itemName}, index) => {
        return template.innerHTML
          .replace(/\\{\\{\\s*${itemName}\\s*\\}\\}/g, ${itemName})
          .replace(/\\{\\{\\s*index\\s*\\}\\}/g, index);
      }).join('');
      el.innerHTML = html;
    }
  }`;
  }
  
  /**
   * Generate binding update
   */
  private generateBindingUpdate(elementId: string, expr: ElementExpression): string {
    const stateKey = expr.expression;
    
    return `
  if (el.getAttribute('data-hjx-id') === '${elementId}') {
    if (el.tagName === 'INPUT' || el.tagName === 'SELECT' || el.tagName === 'TEXTAREA') {
      el.value = ${stateKey}.get() ?? '';
    }
  }`;
  }
  
  /**
   * Convert HJX condition to JavaScript
   */
  private convertConditionToJS(condition: string): string {
    return condition
      .replace(/\&\&/g, '&&')
      .replace(/\|\|/g, '||')
      .replace(/===/g, '===')
      .replace(/\!==/g, '!==')
      .replace(/\b([A-Za-z_][A-Za-z0-9_]*)\b/g, (match) => {
        if (this.graph.stateToElements.has(match) || this.graph.computedDeps.has(match)) {
          return `${match}.get()`;
        }
        return match;
      });
  }
  
  /**
   * Get all computed values that depend on a state key
   */
  private getComputedDependents(key: string): string[] {
    const dependents: string[] = [];
    this.graph.computedDeps.forEach((deps, computed) => {
      if (deps.has(key)) {
        dependents.push(computed);
      }
    });
    return dependents;
  }
  
  /**
   * Get DOM updates for computed value changes
   */
  private getComputedElementUpdates(computedKey: string): string {
    const elements = this.graph.stateToElements.get(computedKey) || new Set();
    if (elements.size === 0) return '';
    
    const updates: string[] = [];
    elements.forEach(elementId => {
      const expressions = this.graph.elementExpressions.get(elementId) || [];
      expressions.forEach(expr => {
        if (expr.dependencies.has(computedKey)) {
          updates.push(this.generateElementUpdate(elementId, expr));
        }
      });
    });
    
    const elementIds = Array.from(elements).join('"], [data-hjx-id="');
    return `
  // Update DOM for ${computedKey}
  const elements = document.querySelectorAll('[data-hjx-id="${elementIds}"]');
  elements.forEach(el => {
    ${updates.join('\n    ')}
  });`;
  }
  
  /**
   * Generate handler wrappers with batching
   */
  private generateHandlerWrappers(): string {
    if (Object.keys(this.handlers).length === 0) {
      return '// No handlers';
    }
    
    const wrappers: string[] = [];
    
    for (const [handlerName, handler] of Object.entries(this.handlers)) {
      const modified = this.graph.handlerEffects.get(handlerName) || new Set();
      const modifiedArray = Array.from(modified);
      
      // Compile handler body
      const handlerBody = this.compileHandlerBody(handler.body || []);
      
      wrappers.push(`
// Handler: ${handlerName} (modifies: ${modifiedArray.join(', ') || 'none'})
window.${handlerName} = function(event, element) {
  batch(() => {
    ${handlerBody}
  });
};`);
    }
    
    return wrappers.join('\n');
  }
  
  /**
   * Compile handler body from HJX DSL to JavaScript
   */
  private compileHandlerBody(lines: string[]): string {
    const jsLines: string[] = [];

    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;

      // set count++
      const incMatch = trimmed.match(/^set\s+([A-Za-z_][A-Za-z0-9_]*)\+\+$/);
      if (incMatch) {
        jsLines.push(`    ${incMatch[1]}.set(${incMatch[1]}.get() + 1);`);
        continue;
      }

      // set count += value
      const compoundMatch = trimmed.match(/^set\s+([A-Za-z_][A-Za-z0-9_]*)\s*\+=\s*(.+)$/);
      if (compoundMatch) {
        jsLines.push(`    ${compoundMatch[1]}.set(${compoundMatch[1]}.get() + ${this.convertExpression(compoundMatch[2])});`);
        continue;
      }

      // set count = expression
      const setMatch = trimmed.match(/^set\s+([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.+)$/);
      if (setMatch) {
        const convertedExpr = this.convertExpression(setMatch[2]);
        jsLines.push(`    ${setMatch[1]}.set(${convertedExpr});`);
        continue;
      }

      // log "message"
      const logMatch = trimmed.match(/^log\s+(.+)$/);
      if (logMatch) {
        jsLines.push(`    console.log(${logMatch[1]});`);
        continue;
      }

      // batch: { ... }
      if (trimmed === 'batch:') {
        jsLines.push(`    batch(() => {`);
        continue;
      }

      // Unknown line - preserve as comment
      jsLines.push(`    // ${trimmed}`);
    }

    return jsLines.join('\n');
  }
  
  /**
   * Generate development tools
   */
  private generateDevTools(): string {
    const stateToElements = Array.from(this.graph.stateToElements.entries())
      .map(([k, v]) => [k, Array.from(v)]);
    const computedDeps = Array.from(this.graph.computedDeps.entries())
      .map(([k, v]) => [k, Array.from(v)]);
    
    return `
// Development tools
(function() {
  if (typeof window === 'undefined') return;
  
  window.__HJX = window.__HJX || {};
  window.__HJX_DEV__ = window.__HJX_DEV__ || false;
  
  window.__HJX_graph__ = {
    stateToElements: ${JSON.stringify(stateToElements)},
    computedDeps: ${JSON.stringify(computedDeps)},
    metrics: ${JSON.stringify(this.graph.metrics)}
  };
  
  window.__HJX_SIGNALS__ = {
    ${Array.from(this.graph.stateToElements.keys()).map(key => 
      `get ${key}() { return typeof ${key} !== 'undefined' ? ${key}.get() : undefined; },\n    set ${key}(val) { if (typeof ${key} !== 'undefined') ${key}.set(val); }`
    ).join(',\n    ')}
  };

  window.__HJX_VISUALIZE__ = function() {
    if (!window.__HJX_DEV__) {
      console.warn('HJX DevTools: Set window.__HJX_DEV__ = true to enable visualization');
      console.log('Basic info:', window.__HJX_graph__);
      return;
    }
    
    console.clear();
    console.log('%c🔍 HJX Dependency Visualizer', 'font-size: 16px; font-weight: bold; color: #3b82f6;');
    console.log('');
    
    console.group('📊 Component Metrics');
    console.log('Total Elements:', window.__HJX_graph__.metrics.totalElements);
    console.log('Total Expressions:', window.__HJX_graph__.metrics.totalExpressions);
    console.log('Hot States:', window.__HJX_graph__.metrics.hotStates.join(', ') || 'none');
    console.groupEnd();
  };
  
  if (window.__HJX_DEV__) {
    console.log('%c✨ HJX DevTools Active', 'background: #3b82f6; color: white; padding: 4px 8px; border-radius: 4px;');
  }
})();`;
  }
  
  /**
   * Generate footer with cleanup
   */
  private generateFooter(): string {
    const stateKeys = Array.from(this.graph.stateToElements.keys());
    
    return `
// Cleanup registry
window.__hjx_cleanups = window.__hjx_cleanups || [];

// Export for testing
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { ${stateKeys.join(', ')} };
}`;
  }
}