// Generated by HJX v0.1 (server-driven)
import { createRemoteStore } from "./runtime.js";

const initialState = {};

function getByPath(obj, path) {
  return path.split(".").reduce((acc, part) => acc && acc[part], obj);
}

export function createApp(rootEl) {
  const protocol = location.protocol === "https:" ? "wss:" : "ws:";
  const wsUrl = protocol + "//" + location.host + "/hjx";

  const store = createRemoteStore(wsUrl, initialState, rootEl);

  window._hjx_rebind = () => {
    // Clean up old subscriptions
    if (window._hjx_unsubs) window._hjx_unsubs.forEach(fn => fn());
    window._hjx_unsubs = [];

    // Discover and bind text interpolations from data-hjx-text attributes
    rootEl.querySelectorAll("[data-hjx-text]").forEach(el => {
      const template = el.getAttribute("data-hjx-text");
      const render = () => {
        const s = store.get();
        el.textContent = template.replace(/\{\{\s*([A-Za-z_][A-Za-z0-9_.]*)\s*\}\}/g, (_, key) => String(getByPath(s, key) ?? ""));
      };
      render();
      window._hjx_unsubs.push(store.subscribe(render));
    });

    // Discover and bind attribute interpolations from data-hjx-bind-* attributes
    rootEl.querySelectorAll("*").forEach(el => {
      for (const attr of Array.from(el.attributes)) {
        if (attr.name.startsWith("data-hjx-bind-")) {
          const targetAttr = attr.name.slice("data-hjx-bind-".length);
          const template = attr.value;
          const render = () => {
            const s = store.get();
            const out = template.replace(/\{\{\s*([A-Za-z_][A-Za-z0-9_.]*)\s*\}\}/g, (_, key) => String(getByPath(s, key) ?? ""));
            if (out === "false" || out === "null" || out === "undefined") {
              el.removeAttribute(targetAttr);
            } else {
              el.setAttribute(targetAttr, out);
            }
            if (targetAttr === "value" && "value" in el) el.value = out;
          };
          render();
          window._hjx_unsubs.push(store.subscribe(render));
        }
      }
    });

    // Discover and bind click handlers from data-hjx-click attributes
    rootEl.querySelectorAll("[data-hjx-click]").forEach(el => {
      const handler = el.getAttribute("data-hjx-click");
      el.addEventListener("click", (e) => {
        const payload = {};
        // forward dataset keys (like data-hjx-idx) to server
        if (el.dataset) {
          for (const k of Object.keys(el.dataset)) payload[k] = el.dataset[k];
        }
        store.sendEvent(handler, payload);
      });
    });

    // Discover and bind input bindings from data-hjx-input attributes
    rootEl.querySelectorAll("[data-hjx-input]").forEach(el => {
      const stateKey = el.getAttribute("data-hjx-input");
      el.addEventListener("input", (e) => {
        store.set({ [stateKey]: e.target.value });
      });
      const render = () => {
        const s = store.get();
        const v = getByPath(s, stateKey) ?? "";
        if (el.value !== String(v)) el.value = String(v);
      };
      render();
      window._hjx_unsubs.push(store.subscribe(render));
    });
  };

  window._hjx_rebind();
  return { store };
}

export function mountApp() {
  const root = document.getElementById("app");
  if (!root) throw new Error("Missing #app");
  root.setAttribute("data-hjx-scope", "hjx-counter");
  root.innerHTML = "<div data-hjx-id=\"hjx-counter-0\" data-hjx-scope=\"hjx-counter\" id=\"root\" class=\"card\"><span data-hjx-id=\"hjx-counter-1\" data-hjx-scope=\"hjx-counter\" class=\"title\" data-hjx-text=\"Count: {{count}}\">Count: 0</span><button data-hjx-id=\"hjx-counter-2\" data-hjx-scope=\"hjx-counter\" class=\"primary\" data-hjx-click=\"inc\">Increase</button><button data-hjx-id=\"hjx-counter-3\" data-hjx-scope=\"hjx-counter\" class=\"ghost\" data-hjx-click=\"dec\">Decrease</button></div>";
  createApp(root);
}

mountApp();


// NOTE: also emit runtime.js in output.
